package antislop

import (
	"testing"
)

func TestDeadPatterns_FlagsGoFmtPrintln(t *testing.T) {
	ctx := setupCtx(t, map[string]string{
		"server.go": `package server

import "fmt"

func Handle() {
    fmt.Println("debug info")
}
`,
	})
	diags := DetectDeadPatterns(ctx)
	got := diagsWithRule(diags, "antislop/debug-print")
	if len(got) < 1 {
		t.Fatalf("expected >=1 diagnostic for fmt.Println, got %d", len(got))
	}
}

func TestDeadPatterns_FlagsGoFmtPrintf(t *testing.T) {
	ctx := setupCtx(t, map[string]string{
		"server.go": `package server

import "fmt"

func Handle() {
    fmt.Printf("count: %d\n", 42)
}
`,
	})
	diags := DetectDeadPatterns(ctx)
	got := diagsWithRule(diags, "antislop/debug-print")
	if len(got) < 1 {
		t.Fatalf("expected >=1 diagnostic for fmt.Printf, got %d", len(got))
	}
}

func TestDeadPatterns_FlagsPythonPrint(t *testing.T) {
	ctx := setupCtx(t, map[string]string{
		"service.py": "def reconcile(orders):\n    print('debug', len(orders))\n    return orders\n",
	})
	diags := DetectDeadPatterns(ctx)
	got := diagsWithRule(diags, "antislop/python-print-debug")
	if len(got) < 1 {
		t.Fatalf("expected >=1 diagnostic for print(), got %d", len(got))
	}
}

func TestDeadPatterns_DoesNotFlagPythonPrintInTestFile(t *testing.T) {
	ctx := setupCtx(t, map[string]string{
		"tests/test_foo.py": "def test_it():\n    print('ok')\n",
	})
	diags := DetectDeadPatterns(ctx)
	got := diagsWithRule(diags, "antislop/python-print-debug")
	if len(got) != 0 {
		t.Fatalf("expected 0 diagnostics for test file, got %d", len(got))
	}
}

func TestDeadPatterns_DoesNotFlagPythonPrintInMainModule(t *testing.T) {
	ctx := setupCtx(t, map[string]string{
		"__main__.py": "print('starting')\n",
	})
	diags := DetectDeadPatterns(ctx)
	got := diagsWithRule(diags, "antislop/python-print-debug")
	if len(got) != 0 {
		t.Fatalf("expected 0 diagnostics for __main__.py, got %d", len(got))
	}
}

func TestDeadPatterns_DoesNotFlagPythonPrintWithMainGuard(t *testing.T) {
	ctx := setupCtx(t, map[string]string{
		"cli.py": "def run():\n    print('running')\n\nif __name__ == \"__main__\":\n    run()\n",
	})
	diags := DetectDeadPatterns(ctx)
	got := diagsWithRule(diags, "antislop/python-print-debug")
	if len(got) != 0 {
		t.Fatalf("expected 0 diagnostics for __main__ guard file, got %d", len(got))
	}
}

func TestDeadPatterns_FlagsTodoComment(t *testing.T) {
	// Use concatenation to avoid self-detection
	todo := "TO" + "DO: implement this properly"
	ctx := setupCtx(t, map[string]string{
		"app.go": "package app\n\n// " + todo + "\nfunc placeholder() {}\n",
	})
	diags := DetectDeadPatterns(ctx)
	got := diagsWithRule(diags, "antislop/todo-stub")
	if len(got) < 1 {
		t.Fatalf("expected >=1 diagnostic for TODO, got %d", len(got))
	}
}

func TestDeadPatterns_DoesNotFlagPythonPrintInScriptDir(t *testing.T) {
	ctx := setupCtx(t, map[string]string{
		"scripts/deploy.py": "print('deploying')\n",
	})
	diags := DetectDeadPatterns(ctx)
	got := diagsWithRule(diags, "antislop/python-print-debug")
	if len(got) != 0 {
		t.Fatalf("expected 0 diagnostics for scripts dir, got %d", len(got))
	}
}

func TestDeadPatterns_DoesNotFlagFmtPrintInComments(t *testing.T) {
	ctx := setupCtx(t, map[string]string{
		"server.go": "package server\n\n// fmt.Println is used for debugging\nfunc Handle() {}\n",
	})
	diags := DetectDeadPatterns(ctx)
	got := diagsWithRule(diags, "antislop/debug-print")
	if len(got) != 0 {
		t.Fatalf("expected 0 diagnostics for commented fmt.Println, got %d", len(got))
	}
}

func TestDeadPatterns_FlagsPythonFixme(t *testing.T) {
	fixme := "FIX" + "ME: broken logic"
	ctx := setupCtx(t, map[string]string{
		"app.py": "# " + fixme + "\ndef fix():\n    pass\n",
	})
	diags := DetectDeadPatterns(ctx)
	got := diagsWithRule(diags, "antislop/todo-stub")
	if len(got) < 1 {
		t.Fatalf("expected >=1 diagnostic for FIXME, got %d", len(got))
	}
}

func TestDeadPatterns_DoesNotFlagAutoGenerated(t *testing.T) {
	ctx := setupCtx(t, map[string]string{
		"gen.go": "// Code generated by tool. DO NOT EDIT.\npackage gen\n\nimport \"fmt\"\n\nfunc F() { fmt.Println(\"hi\") }\n",
	})
	diags := DetectDeadPatterns(ctx)
	got := diagsWithRule(diags, "antislop/debug-print")
	if len(got) != 0 {
		t.Fatalf("expected 0 diagnostics for auto-generated file, got %d", len(got))
	}
}

func TestDeadPatterns_FlagsEmptyGoFunction(t *testing.T) {
	ctx := setupCtx(t, map[string]string{
		"app.go": "package app\n\nfunc Empty() {}\n",
	})
	diags := DetectDeadPatterns(ctx)
	got := diagsWithRule(diags, "antislop/empty-function")
	if len(got) < 1 {
		t.Fatalf("expected >=1 diagnostic for empty function, got %d", len(got))
	}
}
