package antislop

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/matej/antislop/engine"
)

const panicIntentLookback = 3

func detectPackageName(lines []string) string {
	for _, line := range lines {
		t := strings.TrimLeft(line, " \t")
		if !strings.HasPrefix(t, "package ") && !strings.HasPrefix(t, "package\t") {
			continue
		}
		rest := strings.TrimLeft(t[len("package"):], " \t")
		name := extractWordAt(rest, 0)
		if name != "" {
			return name
		}
	}
	return ""
}

// isCommentLine checks if a line is a Go comment (leading whitespace + //)
func isCommentLine(line string) bool {
	return strings.HasPrefix(strings.TrimLeft(line, " \t"), "//")
}

// containsPanicCall checks for panic( with a word boundary before it.
func containsPanicCall(line string) bool {
	return containsWordThenParen(line, "panic") >= 0
}

// isShortStringPanic checks for panic("...") where the string is 1-40 chars.
func isShortStringPanic(line string) bool {
	idx := containsWordThenParen(line, "panic")
	if idx < 0 {
		return false
	}
	// Find the opening paren
	after := idx + len("panic")
	for after < len(line) && (line[after] == ' ' || line[after] == '\t') {
		after++
	}
	if after >= len(line) || line[after] != '(' {
		return false
	}
	after++ // skip '('
	// Skip optional whitespace
	for after < len(line) && (line[after] == ' ' || line[after] == '\t') {
		after++
	}
	// Expect opening quote
	if after >= len(line) || line[after] != '"' {
		return false
	}
	after++ // skip '"'
	// Count string chars until closing quote
	strLen := 0
	for after < len(line) && line[after] != '"' {
		if line[after] == '\\' {
			after++ // skip escaped char
		}
		strLen++
		after++
	}
	if after >= len(line) || line[after] != '"' {
		return false
	}
	after++ // skip closing '"'
	// Skip optional whitespace + closing paren
	for after < len(line) && (line[after] == ' ' || line[after] == '\t') {
		after++
	}
	if after >= len(line) || line[after] != ')' {
		return false
	}
	return strLen >= 1 && strLen <= 40
}

// isNilGuardLine checks if line matches: if <identifier> == nil {
func isNilGuardLine(line string) bool {
	t := strings.TrimLeft(line, " \t")
	if !strings.HasPrefix(t, "if ") && !strings.HasPrefix(t, "if\t") {
		return false
	}
	rest := strings.TrimLeft(t[2:], " \t")
	// Scan identifier (may contain dots and optional ())
	i := 0
	for i < len(rest) && (isWordChar(rest[i]) || rest[i] == '.') {
		i++
	}
	if i == 0 {
		return false
	}
	// Optional ()
	r := strings.TrimLeft(rest[i:], " \t")
	r = strings.TrimPrefix(r, "()")
	// Expect == nil
	r = strings.TrimLeft(r, " \t")
	if !strings.HasPrefix(r, "==") {
		return false
	}
	r = strings.TrimLeft(r[2:], " \t")
	if !strings.HasPrefix(r, "nil") {
		return false
	}
	r = r[3:]
	// Rest should be optional whitespace, optional {, optional whitespace
	r = strings.TrimSpace(r)
	return r == "" || r == "{"
}

func hasIntentCommentGo(lines []string, panicLineIdx int) bool {
	start := panicLineIdx - panicIntentLookback
	if start < 0 {
		start = 0
	}
	for j := panicLineIdx - 1; j >= start; j-- {
		if isCommentLine(lines[j]) {
			return true
		}
	}
	return false
}

func isNilGuardPanic(lines []string, panicLineIdx int, line string) bool {
	if !isShortStringPanic(line) {
		return false
	}
	for j := panicLineIdx - 1; j >= max(0, panicLineIdx-2); j-- {
		prev := lines[j]
		if strings.TrimSpace(prev) == "" {
			continue
		}
		return isNilGuardLine(prev)
	}
	return false
}

func flagLibraryPanic(lines []string, relPath, pkg string) []engine.Diagnostic {
	if pkg == "main" {
		return nil
	}

	var diags []engine.Diagnostic
	for i, line := range lines {
		if isCommentLine(line) {
			continue
		}
		if !containsPanicCall(line) {
			continue
		}
		if hasIntentCommentGo(lines, i) {
			continue
		}
		if isNilGuardPanic(lines, i, line) {
			continue
		}
		diags = append(diags, engine.Diagnostic{
			FilePath: relPath,
			Engine:   engine.EngineAntislop,
			Rule:     "antislop/go-library-panic",
			Severity: engine.SeverityWarning,
			Message:  fmt.Sprintf("`panic()` in package `%s` (non-main, non-test). Library code should return errors, not unwind the goroutine.", pkg),
			Help:     "Convert to `return fmt.Errorf(...)` (or a wrapped error) and let the caller decide. Reserve `panic` for genuinely-impossible states.",
			Line:     i + 1,
			Column:   1,
			Category: "Antislop",
		})
	}
	return diags
}

func DetectGoPatterns(ctx engine.EngineContext) []engine.Diagnostic {
	var diags []engine.Diagnostic

	for _, filePath := range ctx.Files {
		if filepath.Ext(filePath) != ".go" {
			continue
		}
		if strings.HasSuffix(filePath, "_test.go") {
			continue
		}
		content, err := readFile(filePath)
		if err != nil {
			continue
		}
		if isAutoGenerated(content) || isIgnoredFile(content) {
			continue
		}
		lines := strings.Split(content, "\n")
		pkg := detectPackageName(lines)
		if pkg == "" {
			continue
		}
		relPath := relativePath(ctx.RootDir, filePath)
		diags = append(diags, flagLibraryPanic(lines, relPath, pkg)...)
	}

	return diags
}
