package antislop

import (
	"os"
	"path/filepath"
	"strings"
)

func readFile(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

func relativePath(root, path string) string {
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return path
	}
	return filepath.ToSlash(rel)
}

func isAutoGenerated(content string) bool {
	lines := strings.SplitN(content, "\n", 6)
	for _, line := range lines {
		lower := strings.ToLower(line)
		if strings.Contains(lower, "generated") || strings.Contains(lower, "do not edit") || strings.Contains(lower, "auto-generated") {
			return true
		}
	}
	return false
}

func isIgnoredFile(content string) bool {
	lines := strings.SplitN(content, "\n", 4)
	for _, line := range lines {
		if strings.Contains(line, "antislop-ignore-file") {
			return true
		}
	}
	return false
}

func IsNonProductionPath(relPath string) bool {
	parts := strings.Split(filepath.ToSlash(relPath), "/")
	nonProdDirs := map[string]bool{
		"scripts": true, "bin": true, "examples": true, "example": true,
		"demos": true, "demo": true, "bench": true, "benchmarks": true,
		"fixtures": true, "testdata": true, "third_party": true,
	}
	for _, p := range parts {
		if nonProdDirs[p] {
			return true
		}
	}
	return false
}

// isWordChar checks if a byte is [a-zA-Z0-9_].
func isWordChar(b byte) bool {
	return (b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z') || (b >= '0' && b <= '9') || b == '_'
}

// hasWordBoundaryBefore checks that there is a word boundary before position idx in s.
func hasWordBoundaryBefore(s string, idx int) bool {
	if idx == 0 {
		return true
	}
	return !isWordChar(s[idx-1])
}

// containsWordThenParen finds "word" with a word boundary before it,
// then optional whitespace, then '('. Returns the index of the match or -1.
func containsWordThenParen(line, word string) int {
	start := 0
	for {
		idx := strings.Index(line[start:], word)
		if idx < 0 {
			return -1
		}
		idx += start
		if !hasWordBoundaryBefore(line, idx) {
			start = idx + len(word)
			continue
		}
		after := idx + len(word)
		// skip whitespace
		for after < len(line) && (line[after] == ' ' || line[after] == '\t') {
			after++
		}
		if after < len(line) && line[after] == '(' {
			return idx
		}
		start = idx + len(word)
	}
}

// extractFirstWord returns the first whitespace-delimited token from s.
func extractFirstWord(s string) string {
	s = strings.TrimLeft(s, " \t")
	end := strings.IndexAny(s, " \t\n\r")
	if end < 0 {
		return s
	}
	return s[:end]
}

// extractWordAt extracts a contiguous [a-zA-Z0-9_]+ token starting at position idx.
func extractWordAt(s string, idx int) string {
	end := idx
	for end < len(s) && isWordChar(s[end]) {
		end++
	}
	return s[idx:end]
}

// startsWithKeyword checks if trimmed starts with any of the keywords
// followed by a non-word character. Returns the matched keyword or "".
func startsWithKeyword(trimmed string, keywords []string) string {
	for _, kw := range keywords {
		if !strings.HasPrefix(trimmed, kw) {
			continue
		}
		if len(trimmed) == len(kw) {
			return kw
		}
		if !isWordChar(trimmed[len(kw)]) {
			return kw
		}
	}
	return ""
}

// isPyDefLine checks if a line is a Python def or async def, returns the function name.
func isPyDefLine(line string) (string, bool) {
	t := strings.TrimLeft(line, " \t")
	if strings.HasPrefix(t, "async ") || strings.HasPrefix(t, "async\t") {
		t = strings.TrimLeft(t[5:], " \t")
	}
	if !strings.HasPrefix(t, "def ") && !strings.HasPrefix(t, "def\t") {
		return "", false
	}
	rest := strings.TrimLeft(t[3:], " \t")
	name := extractWordAt(rest, 0)
	if name == "" {
		return "", false
	}
	return name, true
}

// containsAnyWord checks if any word in the text (split on non-word chars)
// is present in the wordSet. Text is assumed to be already lowercased.
func containsAnyWord(lowerText string, wordSet map[string]bool) bool {
	start := -1
	for i := 0; i <= len(lowerText); i++ {
		if i < len(lowerText) && isWordChar(lowerText[i]) {
			if start < 0 {
				start = i
			}
		} else {
			if start >= 0 {
				word := lowerText[start:i]
				if wordSet[word] {
					return true
				}
				start = -1
			}
		}
	}
	return false
}
