package antislop

import (
	"path/filepath"
	"strings"

	"github.com/matej/antislop/engine"
)

type commentBlock struct {
	startLine        int
	rawLines         []string
	prose            []string
	nextNonBlankLine string
}

func collectLineCommentBlocks(lines []string, marker string) []commentBlock {
	var blocks []commentBlock
	var current *commentBlock

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, marker) && !strings.HasPrefix(trimmed, marker+"!") {
			body := strings.TrimSpace(trimmed[len(marker):])
			if current == nil {
				current = &commentBlock{startLine: i + 1}
			}
			current.rawLines = append(current.rawLines, trimmed)
			current.prose = append(current.prose, body)
		} else {
			if current != nil {
				for j := i; j < len(lines); j++ {
					if strings.TrimSpace(lines[j]) != "" {
						current.nextNonBlankLine = lines[j]
						break
					}
				}
				blocks = append(blocks, *current)
				current = nil
			}
		}
	}
	if current != nil {
		blocks = append(blocks, *current)
	}
	return blocks
}

func isBlockExempt(block commentBlock, ext string) bool {
	if looksLikeGoDoc(block, ext) {
		return true
	}
	if block.startLine == 1 {
		joined := strings.ToLower(strings.Join(block.rawLines, " "))
		if strings.Contains(joined, "copyright") || strings.Contains(joined, "license") {
			return true
		}
	}
	for _, l := range block.rawLines {
		lower := strings.ToLower(l)
		if strings.Contains(lower, "biome-ignore") || strings.Contains(lower, "eslint-disable") ||
			strings.Contains(lower, "noqa") || strings.Contains(lower, "rubocop:disable") ||
			strings.Contains(lower, "antislop-ignore") {
			return true
		}
	}
	return false
}

func detectNarrativeInBlock(block commentBlock, ext string) (bool, string) {
	if isBlockExempt(block, ext) {
		return false, ""
	}

	for _, l := range block.prose {
		if isDecorativeSeparator(l) || isDecorativeSectionHeader(l) {
			return true, "decorative separator"
		}
	}
	for _, l := range block.prose {
		if isSectionHeader(l) {
			return true, "phase/section header"
		}
	}

	joined := strings.Join(block.prose, " ")
	if hasWhyMarker(joined) {
		return false, ""
	}

	isAboveDecl := looksLikeDeclarationPreamble(block.nextNonBlankLine, ext)

	if len(block.prose) >= 3 && isAboveDecl && hasPreambleSlopSignal(block) {
		return true, "multi-line preamble before declaration"
	}
	if containsCrossRefPhrase(joined) {
		return true, "cross-reference commentary"
	}
	for _, l := range block.prose {
		if hasJustificationOpener(l) {
			return true, "justification prose"
		}
	}
	if len(block.rawLines) == 1 && len(block.prose) > 0 && isExplanatoryOpener(block.prose[0]) && isAboveDecl {
		return true, "explanatory preamble"
	}

	nonEmpty := 0
	for _, l := range block.prose {
		if l != "" {
			nonEmpty++
		}
	}
	if nonEmpty >= 5 && !isAboveDecl {
		return true, "long narrative block"
	}
	if nonEmpty >= 3 && !isAboveDecl {
		return true, "multi-line narrative prose"
	}

	return false, ""
}

func DetectNarrativeComments(ctx engine.EngineContext) []engine.Diagnostic {
	var diags []engine.Diagnostic

	for _, filePath := range ctx.Files {
		ext := filepath.Ext(filePath)
		if ext != ".go" && ext != ".py" {
			continue
		}
		content, err := readFile(filePath)
		if err != nil {
			continue
		}
		if isAutoGenerated(content) || isIgnoredFile(content) {
			continue
		}
		relPath := relativePath(ctx.RootDir, filePath)
		if IsNonProductionPath(relPath) {
			continue
		}

		lines := strings.Split(content, "\n")
		marker := "//"
		if ext == ".py" {
			marker = "#"
		}

		blocks := collectLineCommentBlocks(lines, marker)
		for _, block := range blocks {
			matched, reason := detectNarrativeInBlock(block, ext)
			if !matched {
				continue
			}
			diags = append(diags, engine.Diagnostic{
				FilePath: relPath,
				Engine:   engine.EngineAntislop,
				Rule:     "antislop/narrative-comment",
				Severity: engine.SeverityWarning,
				Message:  "Narrative comment block (" + reason + ")",
				Help:     "Remove — narrative/decorative comments belong in PR descriptions, not source. Code should be self-explanatory.",
				Line:     block.startLine,
				Category: "Comments",
				Fixable:  true,
			})
		}
	}

	return diags
}
