package util

import (
	"bufio"
	"os"
	"path/filepath"
	"strings"
)

var defaultExclude = map[string]bool{
	"vendor":        true,
	".git":          true,
	"node_modules":  true,
	"dist":          true,
	"build":         true,
	"__pycache__":   true,
	".mypy_cache":   true,
	".pytest_cache": true,
	"testdata":      false, // keep but flaggable
}

func CollectSourceFiles(root string, include, exclude []string, languages []string) ([]string, error) {
	excludeSet := map[string]bool{}
	for _, e := range exclude {
		excludeSet[e] = true
	}

	extSet := map[string]bool{}
	for _, lang := range languages {
		switch lang {
		case "go":
			extSet[".go"] = true
		case "python":
			extSet[".py"] = true
		}
	}

	var files []string
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			name := d.Name()
			if excludeSet[name] || defaultExclude[name] {
				return filepath.SkipDir
			}
			return nil
		}
		name := d.Name()
		if isTestFile(name) {
			return nil
		}
		ext := filepath.Ext(path)
		if !extSet[ext] {
			return nil
		}
		files = append(files, path)
		return nil
	})
	return files, err
}

func isTestFile(name string) bool {
	return strings.HasSuffix(name, "_test.go") ||
		strings.HasPrefix(name, "test_") ||
		strings.HasSuffix(name, "_test.py") ||
		name == "conftest.py"
}

func IsAutoGenerated(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	lines := 0
	for scanner.Scan() && lines < 5 {
		line := strings.ToLower(scanner.Text())
		if strings.Contains(line, "generated") || strings.Contains(line, "do not edit") || strings.Contains(line, "auto-generated") {
			return true
		}
		lines++
	}
	return false
}

func IsNonProductionPath(relPath string) bool {
	parts := strings.Split(filepath.ToSlash(relPath), "/")
	nonProdDirs := map[string]bool{
		"scripts": true, "bin": true, "examples": true, "example": true,
		"demos": true, "demo": true, "bench": true, "benchmarks": true,
		"fixtures": true, "__fixtures__": true, "__mocks__": true,
		"__tests__": true, "vendor": true, "third_party": true,
	}
	for _, p := range parts {
		if nonProdDirs[p] {
			return true
		}
	}
	return false
}
