package util

import (
	"bufio"
	"os"
	"path/filepath"
	"strings"
)

var defaultExclude = map[string]bool{
	"vendor":        true,
	".git":          true,
	"node_modules":  true,
	"dist":          true,
	"build":         true,
	"__pycache__":   true,
	".mypy_cache":   true,
	".pytest_cache": true,
	".venv":         true,
	"venv":          true,
	".env":          true,
	"env":           true,
	".tox":          true,
	"site-packages": true,
	".eggs":         true,
	".nox":          true,
	"third_party":   true,
	"external":      true,
	"target":        true,
}

func CollectSourceFiles(root string, include, exclude []string, languages []string) ([]string, error) {
	excludeNames := map[string]bool{}
	var excludePaths []string
	for _, e := range exclude {
		if strings.Contains(e, "/") || strings.Contains(e, string(filepath.Separator)) {
			excludePaths = append(excludePaths, filepath.Clean(e))
		} else {
			excludeNames[e] = true
		}
	}

	extSet := map[string]bool{}
	for _, lang := range languages {
		switch lang {
		case "go":
			extSet[".go"] = true
		case "python":
			extSet[".py"] = true
		}
	}

	var files []string
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}

		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return nil
		}
		rel = filepath.ToSlash(rel)

		if d.IsDir() {
			name := d.Name()
			if excludeNames[name] || defaultExclude[name] {
				return filepath.SkipDir
			}
			for _, ep := range excludePaths {
				if rel == ep || strings.HasPrefix(rel, ep+"/") {
					return filepath.SkipDir
				}
			}
			return nil
		}
		name := d.Name()
		if isTestFile(name) {
			return nil
		}
		ext := filepath.Ext(path)
		if !extSet[ext] {
			return nil
		}
		files = append(files, path)
		return nil
	})
	return files, err
}

func isTestFile(name string) bool {
	return strings.HasSuffix(name, "_test.go") ||
		strings.HasPrefix(name, "test_") ||
		strings.HasSuffix(name, "_test.py") ||
		name == "conftest.py"
}

func IsAutoGenerated(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	lines := 0
	for scanner.Scan() && lines < 5 {
		line := strings.ToLower(scanner.Text())
		if strings.Contains(line, "generated") || strings.Contains(line, "do not edit") || strings.Contains(line, "auto-generated") {
			return true
		}
		lines++
	}
	return false
}

func IsNonProductionPath(relPath string) bool {
	parts := strings.Split(filepath.ToSlash(relPath), "/")
	nonProdDirs := map[string]bool{
		"scripts": true, "bin": true, "examples": true, "example": true,
		"demos": true, "demo": true, "bench": true, "benchmarks": true,
		"fixtures": true, "__fixtures__": true, "__mocks__": true,
		"__tests__": true, "vendor": true, "third_party": true,
	}
	for _, p := range parts {
		if nonProdDirs[p] {
			return true
		}
	}
	return false
}
